### ISSUE TITLE
Add bagging/stacking/boosting for post-processing

### ISSUE THREAD

**Issue by guwenyu1996** [sirpandemona/CDA#11]

**Comment by sirpandemona** [comment]
Strickly speaking, we're already using bagging when using random forests.

**Comment by guwenyu1996** [comment]
I add this as from description "Explain the applied data pre-processing steps, learning algorithms, and post-processing steps or ensemble methods"
Do we need to apply same ensemble method to all classifiers if we want to compare results from them?
I understand the main goal of post-processing steps is compare the accuracy with and without bagging and see if it helps?
